information = {
    "summoners":[
        "The Boonies",
        "Coffee Cat",
        "Dunk and Dip",
        "Xandyr",
        "Youngst3r Joey",
        "TheMarioPianist",
        "Flashcruise",
        "Frelain",
        "Paperrug",
        "Whatsthedilleeyo",
        "Marunga",
        "GreatContent",
        "Salamander Man",
        "Fitshace",
        "Pandamaster210",
        "MasterChief2001",
        "Captain Insano",
        "Chipper",
        "WhoIsJohnGalt149",
        "Aulzeren0r",
        "Hecrimjob",
        "Snakethorn",
        "shmmyshmmy",
        "JacktheKatmain",
        "Badj33",
        "JediDude",
        "Lemonblossom",
        "Fragerito",
        "Occasus",
        "YungBootyBandit",
        "drew the deity",
        "amt",
        "Wrecked Sai",
        "Quik Quinn",
        "Kaimex",
        "Danskbjørn",
        "Aguymozo",
        "Nightmare Seda",
        "Mrbluellama",
        "GhostOverl0rd",
        "Jácøb",
        "kanyi sin",
        "EvilOcelotz",
        "biiibili",
        "Insecure_Walrus",
        "Yasemin"
    ],
    "accountIds":[
        "s_iVxKJfcLc9BTN6gG6Z_xlJ2ooFkBiAN5lUdpP1y7w2CA",
        "KTsj1bTsMek6XC1EbbZq3nnCRwZumqmUbrA9FVr9nJ1N2g",
        "JXa-PdY-OsrSad5fTpDlz63u88xp0_u7ekrzxcFAASksUJE",
        "dLguM8x84O7kFN6J5W9GoGf5NzAvqzHMNfapSOak_KiV6Zk",
        "4lI5fJemEg0Mty_P75amiByEI2UVOdCoO2bA1UNoItR29MQ",
        "e2Dlp2Q_rKwXW7TiGEG8lRno0Oc41Ip_13GkRCMl02mc3UY",
        "RAxvgRG0MPIhp_-ezNPK9zSvbQz5f--sg5E0Ni88ghO66Lc",
        "2ItskONDnTOp52gQl20c9D8YgzEGYH07EvSveAXh4YsLsV0",
        "vKo7XI1gWEQBx2Ppf1oXRAqY9G98I1KxmImf1WgDKl_1RY1u3lDpdqz9",
        "YnV1lNxITgrRmp0Lu-pJQ3UYNqTHYfOGVdYzFfXndF2iNqynmEvEG1HF",
        "-_Rev6PrZwGRfln9adHpcUy4xTTlO93ooF7jen_SR6Vvkgoz1bZBX6dI",
        "bt0gfFdEDmvNx2KZfVnaXtSDqZvqEOdaAKGskUjTTYb-Ufo",
        "f3ejeD5b6FcMwPj_AKjskcE6JSglLDefARL6WfHj-dmKMg",
        "5A5eB1SZ1qaSb9tFIsPUTXoozLi45ADM2wWNJuDLu3_tkLM",
        "aTkAIK2WGrGprnyynxDEC39VFP0Np_lbN5pQ05Ecj639ww",
        "vk4ZB-YO_xF5bypGQIr4-_1bjlpn-XvHwmPMjUQZ2w46Qw",
        "dlR4wmF_G4J7UxaczFPzYZCR0bQB7jFSXnUlFq2R5KQ48S0",
        "hlyTYT9EGhcG3kUPQWcNP8Bp2HYHB-d28APxHsYe2L2y3Sk",
        "akSsyPIAtm5kRMRxpeq1jGLavW5YjBUnrUFFtaPMcrP3Jug",
        "ZAkEFymCdq6_s38yD_YIJbRPODZUZsl67MZ6Vn57uHc0m6c",
        "yurC0H09nRXmL1xKvL3DG2KX5fNEhgmJb88ZdjtjQI57aLo",
        "wDoc2eyO-Sk4ufy-KKkxoC-rMHl86qV3_1gzsGUGVXuJv3U",
        "Q1BkGH--hjs1_BCdw8cCHqfZwj8KpqTJXTsyRLYsXYp57YA",
        "ZGKQiVthMqZFMwI5xCr5pGCFr8vMnoqXG1JNEyyY4UnNxzQ",
        "VaHFc6G5GX1qIRURdoDFi2izHZTPF-WR_eRmNbHf38ELYSk",
        "7bRpLhwa419LNuwoWVMC6LWJloh1R1yvo5iGzl9-GMLtfTI",
        "enYVA2e_fc6B9-h9ey78RgXR6Se4P0d-Te2WHtMdLDMKlA",
        "Iqch48BuHZ0xeTSEizQ2mosQN1FGZaW4fUh4g0UjmyDsiZs",
        "DVV6Rfg5CaJPlag6IQI5_O_lrw1HCamnX3bqpIrftB6K4g",
        "PD5kOt3Eo3Baf2HsOl1Y5Nw2AUY7HindorhBeOLUP3gJt-U",
        "jfP-aCGVma0yOMnFn3bdH3-qzsBBhJQJG8p7MZqzoTfRPlI",
        "cCPEEXq3AmjJqyEln2Wd_RjbJanLE63K8bMDD7HleloTyQo",
        "6Og3-De8mL8fJA_Tvipw98oIa2MNTytfukZ5cluEYPxckLY",
        "F-v9WyU6jj-wCuHjvhPT3k6AmU0pluEXyRcBicjR0jEoS8E",
        "xyJlJvm7AQXt6fOlC0EPvuk-FSuAzEUeok2gAAsa3RNVpdg",
        "mgeMhLvN3KQ7ZedGbhD9VBSdqzT6B5V4iajpSHsgkf3m1dg",
        "1Mi1MiBjYHI7t1hQnROAJFJ6YTRQU8XnO5DRVRh6hPzxgW8",
        "ECCmAEJCS5CRL4B2eOp6UGNPO8ztJ6JS1widiUHOBUUJJVo",
        "RkGhFtBLxRemyKt_iyoGqMowJlWuk4Tj-a9Tzi3REFMe11M",
        "rQEaHldvVNIelhPrO0Uw-rPyYBg9gp8NKXXbb8ocwfwPGz8",
        "gs934iEzay8-CjTNqa6Dt6ASnD5_1gOXjfoBq_r-bhXmLEU",
        "dtXDFzXouejxR7eilGvpkoSbRWLRnZ2lAK14diV-ttrjfbY",
        "iqiRWxHwFgI6c7c7ltKQRIOXyo7h4TwSUzDExnANlOrd5S8",
        "fLYpyU-Ou-ZuP1xcr3EHWr0SodnGxQNwNZ5W6ZW3k6eahg",
        "PJI9Qal-Vgi1dfK4gxVQf-00zPjw_hseHbP9gOUbfyM1yA",
        "DhaXaW1lWe6T1ivJnhg1vHPn5f5hOTSbOyYr9m_XgH-1vck"
    ],
    "api key":"RGAPI-7e0c6faa-0390-4f75-b94b-4d4c60123d58",
    "region":"na1"
}
